-- MySQL Script generated by MySQL Workbench
-- Fri May 19 21:40:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EventosFCI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EventosFCI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EventosFCI` DEFAULT CHARACTER SET utf8 ;
USE `EventosFCI` ;

-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Rol` (
  `idRol` CHAR(3) NOT NULL,
  `NombreRol` VARCHAR(40) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Telefono` (
  `idTelefono` INT NOT NULL,
  `TelefonoPersonal` INT(10) NULL,
  `TelefonoCasa` INT(10) NULL,
  PRIMARY KEY (`idTelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Persona` (
  `idmatricula` CHAR(6) NOT NULL,
  `idTelefono` INT NOT NULL,
  `NombrePersona` VARCHAR(45) NULL,
  `ApellidoPersona` VARCHAR(45) NULL,
  `FacultadPersona` VARCHAR(105) NULL,
  PRIMARY KEY (`idmatricula`),
  CONSTRAINT `fk_Persona_Telefono1`
    FOREIGN KEY (`idTelefono`)
    REFERENCES `EventosFCI`.`T_Telefono` (`idTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Usuario` (
  `idmatricula` CHAR(6) NOT NULL,
  `idRol` CHAR(3) NOT NULL,
  `Pass` VARCHAR(255) NULL,
  `EmailUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idmatricula`),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `EventosFCI`.`T_Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Usuario_Persona1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `EventosFCI`.`T_Persona` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `idmatricula` CHAR(6) NOT NULL,
  `idUsuario` CHAR(3) NOT NULL,
  `NombreEvento` VARCHAR(60) NULL,
  `DescripcionEvento` VARCHAR(100) NULL,
  `EstatusEvento` INT NULL,
  `F_Evento` DATE NULL,
  PRIMARY KEY (`idEvento`),
  CONSTRAINT `fk_T_Evento_T_Usuario1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `EventosFCI`.`T_Usuario` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Parametro` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `nombreParametro` VARCHAR(100) NULL,
  `DescripcionParametro` VARCHAR(200) NULL,
  PRIMARY KEY (`idParametro`),
  UNIQUE INDEX `idParametro_UNIQUE` (`idParametro` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Juez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Juez` (
  `idJuez` INT NOT NULL,
  `idmatricula` CHAR(6) NOT NULL,
  PRIMARY KEY (`idJuez`),
  UNIQUE INDEX `idjuez_UNIQUE` (`idJuez` ASC),
  CONSTRAINT `fk_T_Juez_Persona1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `EventosFCI`.`T_Persona` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece_Juez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece_Juez` (
  `idEvento` INT NOT NULL,
  `idJuez` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idJuez`),
  CONSTRAINT `fk_evento_has_juez_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `EventosFCI`.`T_Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Pertenece_Juez_T_Juez1`
    FOREIGN KEY (`idJuez`)
    REFERENCES `EventosFCI`.`T_Juez` (`idJuez`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `idEvento` INT NOT NULL,
  `idEquipoJefe` INT NOT NULL,
  `nombreEquipo` VARCHAR(60) NULL,
  PRIMARY KEY (`idEquipo`, `idEquipoJefe`),
  CONSTRAINT `fk_equipo_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `EventosFCI`.`T_Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Equipo_T_Equipo1`
    FOREIGN KEY (`idEquipoJefe`)
    REFERENCES `EventosFCI`.`T_Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Calificaciones` (
  `idCalificacion` INT NOT NULL,
  `idParametro` INT NOT NULL,
  `idJuez` INT NOT NULL,
  `idEvento` INT NOT NULL,
  `idEquipo` INT NOT NULL,
  `Calificacion` DECIMAL(2,2) NULL,
  PRIMARY KEY (`idCalificacion`),
  CONSTRAINT `fk_calificaciones_equipo1`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `EventosFCI`.`T_Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_parametro1`
    FOREIGN KEY (`idParametro`)
    REFERENCES `EventosFCI`.`T_Parametro` (`idParametro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_juez1`
    FOREIGN KEY (`idJuez`)
    REFERENCES `EventosFCI`.`T_Juez` (`idJuez`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `EventosFCI`.`T_Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece_Equipo` (
  `idEquipo` INT NOT NULL,
  `idmatricula` CHAR(6) NOT NULL,
  PRIMARY KEY (`idEquipo`),
  CONSTRAINT `fk_equipo_has_usuario_equipo1`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `EventosFCI`.`T_Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Pertenece_Equipo_T_Usuario1`
    FOREIGN KEY (`idmatricula`)
    REFERENCES `EventosFCI`.`T_Usuario` (`idmatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece` (
  `idEvento` INT NOT NULL,
  `idParametro` INT NOT NULL,
  `idPertenece` INT NULL ,
  PRIMARY KEY (`idEvento`, `idParametro`),
  CONSTRAINT `fk_T_Evento_has_T_Parametro_T_Evento1`
    FOREIGN KEY (`idEvento`)
    REFERENCES `EventosFCI`.`T_Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Evento_has_T_Parametro_T_Parametro1`
    FOREIGN KEY (`idParametro`)
    REFERENCES `EventosFCI`.`T_Parametro` (`idParametro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

