-- MySQL Script generated by MySQL Workbench
-- Wed May 17 13:25:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EventosFCI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EventosFCI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EventosFCI` DEFAULT CHARACTER SET utf8 ;
USE `EventosFCI` ;

-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Rol` (
  `idRol` CHAR(3) NOT NULL,
  `NombreRol` VARCHAR(40) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Usuario` (
  `idmatricula` CHAR(6) NOT NULL,
  `idRol` CHAR(3) NOT NULL,
  `NombreUsuario` VARCHAR(80) NULL,
  `Pass` VARCHAR(255) NULL,
  `ApellidoUsuario` VARCHAR(80) NULL,
  `FacultadUsuario` VARCHAR(100) NULL,
  `TelefonoUsuario` CHAR(10) NULL,
  `EmailUsuario` VARCHAR(255) NULL,
  PRIMARY KEY (`idmatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` CHAR(3) NOT NULL,
  `NombreEvento` VARCHAR(60) NULL,
  `DescripcionEvento` VARCHAR(100) NULL,
  `EstatusEvento` INT NULL,
  `F_Evento` DATE NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Parametro` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `nombreParametro` VARCHAR(100) NULL,
  `DescripcionParametro` VARCHAR(200) NULL,
  PRIMARY KEY (`idParametro`),
  UNIQUE INDEX `idParametro_UNIQUE` (`idParametro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Juez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Juez` (
  `idJuez` INT NOT NULL,
  `NombreJuez` VARCHAR(60) NULL,
  `ApellidoJuez` VARCHAR(60) BINARY NULL,
  `Facultad` VARCHAR(200) NULL,
  PRIMARY KEY (`idJuez`),
  UNIQUE INDEX `idjuez_UNIQUE` (`idJuez` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece_Juez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece_Juez` (
  `idEvento` INT NOT NULL,
  `idJuez` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idJuez`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `idEvento` INT NOT NULL,
  `idEncargador` CHAR(1) NULL,
  `nombreEquipo` VARCHAR(60) NULL,
  PRIMARY KEY (`idEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Calificaciones` (
  `idCalificacion` INT NOT NULL,
  `idParametro` INT NOT NULL,
  `idJuez` INT NOT NULL,
  `idEvento` INT NOT NULL,
  `idEquipo` INT NOT NULL,
  `Calificacion` DECIMAL(0,2) NULL,
  PRIMARY KEY (`idCalificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece_Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece_Equipo` (
  `idEquipo` INT NOT NULL,
  `idMatricula` CHAR(6) NOT NULL,
  PRIMARY KEY (`idEquipo`, `idMatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventosFCI`.`T_Pertenece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EventosFCI`.`T_Pertenece` (
  `idEvento` INT NOT NULL,
  `idParametro` INT NOT NULL,
  `idPertenece` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idEvento`, `idParametro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
